# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imagedownloader_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImageDownloaderDialogBase(object):
    def setupUi(self, ImageDownloaderDialogBase):
        ImageDownloaderDialogBase.setObjectName("ImageDownloaderDialogBase")
        ImageDownloaderDialogBase.resize(700, 486)
        ImageDownloaderDialogBase.setStyleSheet("background-color: #000815;\n"
"font-family: sans-serif;")
        self.mainContainer = QtWidgets.QFrame(ImageDownloaderDialogBase)
        self.mainContainer.setGeometry(QtCore.QRect(-1, -1, 701, 450))
        self.mainContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainContainer.setObjectName("mainContainer")
        self.NavBar = QtWidgets.QFrame(self.mainContainer)
        self.NavBar.setGeometry(QtCore.QRect(0, 0, 700, 50))
        self.NavBar.setMinimumSize(QtCore.QSize(700, 40))
        self.NavBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.NavBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.NavBar.setObjectName("NavBar")
        self.downloadNavItem = QtWidgets.QLabel(self.NavBar)
        self.downloadNavItem.setGeometry(QtCore.QRect(20, 10, 150, 40))
        self.downloadNavItem.setMinimumSize(QtCore.QSize(150, 40))
        self.downloadNavItem.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("sans-serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.downloadNavItem.setFont(font)
        self.downloadNavItem.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.downloadNavItem.setStyleSheet("QLabel {\n"
"    background-color: #123;\n"
"    color: #f4f4f4;\n"
"    border: none;\n"
"}\n"
"\n"
"QLabel:hover{\n"
"    background-color: #000815;\n"
"    border-bottom: 2px solid #ff9f00;\n"
"}")
        self.downloadNavItem.setAlignment(QtCore.Qt.AlignCenter)
        self.downloadNavItem.setObjectName("downloadNavItem")
        self.indexNavItem = QtWidgets.QLabel(self.NavBar)
        self.indexNavItem.setGeometry(QtCore.QRect(180, 10, 150, 40))
        self.indexNavItem.setMinimumSize(QtCore.QSize(150, 40))
        self.indexNavItem.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("sans-serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.indexNavItem.setFont(font)
        self.indexNavItem.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.indexNavItem.setStyleSheet("QLabel {\n"
"    background-color: #123;\n"
"    color: #f4f4f4;\n"
"    border: none;\n"
"}\n"
"\n"
"QLabel:hover{\n"
"    background-color: #000815;\n"
"    border-bottom: 2px solid #ff9f00;\n"
"}")
        self.indexNavItem.setAlignment(QtCore.Qt.AlignCenter)
        self.indexNavItem.setObjectName("indexNavItem")
        self.Body = QtWidgets.QFrame(self.mainContainer)
        self.Body.setGeometry(QtCore.QRect(0, 50, 701, 401))
        self.Body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Body.setObjectName("Body")
        self.stackedWidget = QtWidgets.QStackedWidget(self.Body)
        self.stackedWidget.setGeometry(QtCore.QRect(-1, -1, 701, 401))
        self.stackedWidget.setObjectName("stackedWidget")
        self.dowloadPage = QtWidgets.QWidget()
        self.dowloadPage.setObjectName("dowloadPage")
        self.loginContainer = QtWidgets.QFrame(self.dowloadPage)
        self.loginContainer.setGeometry(QtCore.QRect(20, 10, 301, 121))
        self.loginContainer.setStyleSheet("background-color: #f4f4f4;\n"
"")
        self.loginContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loginContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loginContainer.setObjectName("loginContainer")
        self.label = QtWidgets.QLabel(self.loginContainer)
        self.label.setGeometry(QtCore.QRect(0, 0, 301, 31))
        font = QtGui.QFont()
        font.setFamily("sans-serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #123;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.loginInput = QtWidgets.QLineEdit(self.loginContainer)
        self.loginInput.setGeometry(QtCore.QRect(20, 40, 261, 31))
        font = QtGui.QFont()
        font.setFamily("sans-serif")
        font.setPointSize(10)
        self.loginInput.setFont(font)
        self.loginInput.setStyleSheet("QLineEdit {\n"
"    background-color: #fff;\n"
"    border: 1px solid #d1d1d1;\n"
"    padding-left: 8px;\n"
"    color: #012;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-color: #ff9f00;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #ff9f00;\n"
"}\n"
"")
        self.loginInput.setObjectName("loginInput")
        self.passwordInput = QtWidgets.QLineEdit(self.loginContainer)
        self.passwordInput.setGeometry(QtCore.QRect(20, 80, 261, 31))
        font = QtGui.QFont()
        font.setFamily("sans-serif")
        font.setPointSize(10)
        self.passwordInput.setFont(font)
        self.passwordInput.setStyleSheet("QLineEdit {\n"
"    background-color: #fff;\n"
"    border: 1px solid #d1d1d1;\n"
"    padding-left: 8px;\n"
"    color: #012;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-color: #ff9f00;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #ff9f00;\n"
"}\n"
"")
        self.passwordInput.setObjectName("passwordInput")
        self.dateContainer = QtWidgets.QFrame(self.dowloadPage)
        self.dateContainer.setGeometry(QtCore.QRect(20, 140, 301, 101))
        self.dateContainer.setStyleSheet("background-color: #f4f4f4;\n"
"")
        self.dateContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dateContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dateContainer.setObjectName("dateContainer")
        self.label_2 = QtWidgets.QLabel(self.dateContainer)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 301, 31))
        font = QtGui.QFont()
        font.setFamily("sans-serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #123;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.dateEdit = QtWidgets.QDateEdit(self.dateContainer)
        self.dateEdit.setGeometry(QtCore.QRect(80, 30, 201, 26))
        self.dateEdit.setStyleSheet("QComboBox {\n"
"    background-color: #012;\n"
"    border: 1px solid #d1d1d1;\n"
"    padding-left: 8px;\n"
"    color: #f4f4f4;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border-color: #ff9f00;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border-color: #ff9f00;\n"
"}")
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.label_5 = QtWidgets.QLabel(self.dateContainer)
        self.label_5.setGeometry(QtCore.QRect(30, 30, 41, 24))
        font = QtGui.QFont()
        font.setFamily("sans-serif")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: #012;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.dateContainer)
        self.dateEdit_2.setGeometry(QtCore.QRect(80, 60, 201, 26))
        self.dateEdit_2.setStyleSheet("QComboBox {\n"
"    background-color: #012;\n"
"    border: 1px solid #d1d1d1;\n"
"    padding-left: 8px;\n"
"    color: #f4f4f4;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border-color: #ff9f00;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border-color: #ff9f00;\n"
"}")
        self.dateEdit_2.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_2.setCalendarPopup(True)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.label_6 = QtWidgets.QLabel(self.dateContainer)
        self.label_6.setGeometry(QtCore.QRect(30, 60, 41, 24))
        font = QtGui.QFont()
        font.setFamily("sans-serif")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: #012;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.settingsContainer = QtWidgets.QFrame(self.dowloadPage)
        self.settingsContainer.setGeometry(QtCore.QRect(20, 250, 301, 151))
        self.settingsContainer.setStyleSheet("background-color: #f4f4f4;\n"
"")
        self.settingsContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.settingsContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.settingsContainer.setObjectName("settingsContainer")
        self.label_3 = QtWidgets.QLabel(self.settingsContainer)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 301, 31))
        font = QtGui.QFont()
        font.setFamily("sans-serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #123;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(self.settingsContainer)
        self.comboBox.setGeometry(QtCore.QRect(30, 40, 251, 31))
        self.comboBox.setStyleSheet("QComboBox {\n"
"    background-color: #012;\n"
"    border: 1px solid #d1d1d1;\n"
"    padding-left: 8px;\n"
"    color: #f4f4f4;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border-color: #ff9f00;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border-color: #ff9f00;\n"
"}")
        self.comboBox.setCurrentText("")
        self.comboBox.setObjectName("comboBox")
        self.horizontalSlider = QtWidgets.QSlider(self.settingsContainer)
        self.horizontalSlider.setGeometry(QtCore.QRect(30, 110, 201, 22))
        self.horizontalSlider.setStyleSheet("QSlider::handle{\n"
"      background-color: #ff9f00;\n"
"    border: 1px solid #012;\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"}")
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_7 = QtWidgets.QLabel(self.settingsContainer)
        self.label_7.setGeometry(QtCore.QRect(30, 80, 101, 24))
        font = QtGui.QFont()
        font.setFamily("sans-serif")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: #012;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.cloudLabel = QtWidgets.QLabel(self.settingsContainer)
        self.cloudLabel.setGeometry(QtCore.QRect(240, 100, 40, 40))
        font = QtGui.QFont()
        font.setFamily("sans-serif")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.cloudLabel.setFont(font)
        self.cloudLabel.setStyleSheet("color: #012;\n"
"border: 3px solid #012;\n"
"border-top-left-radius: 20px;\n"
"border-top-right-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"border-bottom-right-radius: 20px;\n"
"background-color: #ff9f00;")
        self.cloudLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.cloudLabel.setObjectName("cloudLabel")
        self.outputContainer = QtWidgets.QFrame(self.dowloadPage)
        self.outputContainer.setGeometry(QtCore.QRect(340, 10, 341, 281))
        self.outputContainer.setStyleSheet("background-color: #f4f4f4;\n"
"\n"
"")
        self.outputContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.outputContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.outputContainer.setObjectName("outputContainer")
        self.label_4 = QtWidgets.QLabel(self.outputContainer)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 341, 41))
        font = QtGui.QFont()
        font.setFamily("sans-serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: #012;\n"
"background-color: #f1F1F1;\n"
"border-bottom: 1px solid #d1d1d1;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.resultTable = QtWidgets.QTableWidget(self.outputContainer)
        self.resultTable.setGeometry(QtCore.QRect(10, 50, 321, 221))
        self.resultTable.setAutoFillBackground(False)
        self.resultTable.setStyleSheet("\n"
"QTableWidget{\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    color: #012;\n"
"}")
        self.resultTable.setRowCount(0)
        self.resultTable.setColumnCount(4)
        self.resultTable.setObjectName("resultTable")
        self.resultTable.horizontalHeader().setDefaultSectionSize(79)
        self.resultTable.horizontalHeader().setHighlightSections(False)
        self.resultTable.horizontalHeader().setMinimumSectionSize(60)
        self.resultTable.horizontalHeader().setStretchLastSection(False)
        self.resultTable.verticalHeader().setVisible(False)
        self.resultTable.verticalHeader().setDefaultSectionSize(28)
        self.resultTable.verticalHeader().setHighlightSections(False)
        self.resultTable.verticalHeader().setMinimumSectionSize(25)
        self.resultTable.verticalHeader().setSortIndicatorShown(False)
        self.downloadBtn = QtWidgets.QLabel(self.dowloadPage)
        self.downloadBtn.setGeometry(QtCore.QRect(340, 310, 341, 44))
        self.downloadBtn.setMinimumSize(QtCore.QSize(0, 44))
        self.downloadBtn.setMaximumSize(QtCore.QSize(16777215, 44))
        font = QtGui.QFont()
        font.setFamily("sans-serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.downloadBtn.setFont(font)
        self.downloadBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.downloadBtn.setStyleSheet("QLabel {\n"
"    background-color: #ff9f00;\n"
"    color: #012;\n"
"}\n"
"")
        self.downloadBtn.setAlignment(QtCore.Qt.AlignCenter)
        self.downloadBtn.setObjectName("downloadBtn")
        self.searchBtn = QtWidgets.QLabel(self.dowloadPage)
        self.searchBtn.setGeometry(QtCore.QRect(340, 360, 341, 44))
        self.searchBtn.setMinimumSize(QtCore.QSize(0, 44))
        self.searchBtn.setMaximumSize(QtCore.QSize(16777215, 44))
        font = QtGui.QFont()
        font.setFamily("sans-serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.searchBtn.setFont(font)
        self.searchBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.searchBtn.setStyleSheet("QLabel {\n"
"    background-color: #234;\n"
"    color: #f4f4f4;\n"
"}\n"
"\n"
"QLabel:hover{\n"
"    background-color: #345;\n"
"    color: #f2f2f2;\n"
"}")
        self.searchBtn.setAlignment(QtCore.Qt.AlignCenter)
        self.searchBtn.setObjectName("searchBtn")
        self.stackedWidget.addWidget(self.dowloadPage)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.frame = QtWidgets.QFrame(ImageDownloaderDialogBase)
        self.frame.setGeometry(QtCore.QRect(0, 460, 701, 31))
        self.frame.setStyleSheet("background-color: #101825;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(10, 0, 221, 24))
        font = QtGui.QFont()
        font.setFamily("sans-serif")
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: #ff9f00;")
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")

        self.retranslateUi(ImageDownloaderDialogBase)
        QtCore.QMetaObject.connectSlotsByName(ImageDownloaderDialogBase)

    def retranslateUi(self, ImageDownloaderDialogBase):
        _translate = QtCore.QCoreApplication.translate
        ImageDownloaderDialogBase.setWindowTitle(_translate("ImageDownloaderDialogBase", "Image Downloader"))
        self.downloadNavItem.setText(_translate("ImageDownloaderDialogBase", "Download image"))
        self.indexNavItem.setText(_translate("ImageDownloaderDialogBase", "Index processing"))
        self.label.setText(_translate("ImageDownloaderDialogBase", "Login"))
        self.loginInput.setPlaceholderText(_translate("ImageDownloaderDialogBase", "login"))
        self.passwordInput.setPlaceholderText(_translate("ImageDownloaderDialogBase", "password"))
        self.label_2.setText(_translate("ImageDownloaderDialogBase", "Date"))
        self.dateEdit.setDisplayFormat(_translate("ImageDownloaderDialogBase", "dd-MMM-yyyy"))
        self.label_5.setText(_translate("ImageDownloaderDialogBase", "From"))
        self.dateEdit_2.setDisplayFormat(_translate("ImageDownloaderDialogBase", "dd-MMM-yyyy"))
        self.label_6.setText(_translate("ImageDownloaderDialogBase", "To"))
        self.label_3.setText(_translate("ImageDownloaderDialogBase", "Data sets"))
        self.label_7.setText(_translate("ImageDownloaderDialogBase", "Cloud couverage"))
        self.cloudLabel.setText(_translate("ImageDownloaderDialogBase", "1"))
        self.label_4.setText(_translate("ImageDownloaderDialogBase", "Output"))
        self.downloadBtn.setText(_translate("ImageDownloaderDialogBase", "Download"))
        self.searchBtn.setText(_translate("ImageDownloaderDialogBase", "Search Data"))
        self.label_8.setText(_translate("ImageDownloaderDialogBase", "  Moumen Mohamed  &  Saouidi Ayoub"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ImageDownloaderDialogBase = QtWidgets.QDialog()
    ui = Ui_ImageDownloaderDialogBase()
    ui.setupUi(ImageDownloaderDialogBase)
    ImageDownloaderDialogBase.show()
    sys.exit(app.exec_())
